### ISSUE TITLE
Contact / Verification not working

### ISSUE THREAD

**Issue by The-Skunk** [PH-KDX/flightplandb-py#12]
Sry, but due to the circumstances that no communication (neither verification nor contact) is working on the website https://flightplandatabase.com this is the only option to contact you (or some behalf) to fix this problem. Thanx in advance.

![grafik](https://user-images.githubusercontent.com/37264769/125581647-d817246b-597b-459c-9537-2f207ae588f4.png)

![grafik](https://user-images.githubusercontent.com/37264769/125581700-c10eb491-abe5-4493-bf1b-6d92142e489d.png)

![grafik](https://user-images.githubusercontent.com/37264769/125581723-85d31ad3-b710-4df1-a476-8b9b5f8661d1.png)

**Comment by CreativeSelf0** [comment]
Hey @The-Skunk, sorry to hear that you can't verify your email. 
However, this repo only maintains wrapping the API with python.
We are not sure how the author of the website maintains the verifications process. However, we will look into it if anything new pops we will let you know. Again, sorry for the inconvenience 

Best of Luck.

**Comment by PH-KDX** [comment]
@The-Skunk I've contacted the website developer about this, and he has just sent me an email saying he's fixed it.
Can you confirm that it now works for you?

**Comment by PH-KDX** [comment]
With no answer two weeks later, I'm assuming this issue is done.
