### ISSUE TITLE
Add navaid valid types (for airport)

### ISSUE THREAD

**Issue by devleaks** [PH-KDX/flightplandb-py#14]
When fetching airport info, it sometimes fails because of invalid navaid types.

In a next release, please add 'OM', 'MM', 'IM' as Nav valid types.

Thank you.

**Comment by PH-KDX** [comment]
I've been taking a small break, but I'll fix this on the next release.
Thanks for the info.

**Comment by PH-KDX** [comment]
This should be fixed in https://github.com/PH-KDX/flightplandb-py/commit/aeb6ba109288d1de1fc27a48e6337ddb601df878. I'll release a 0.4.2 with the change once I've addressed #13.
