### ISSUE TITLE
Pip does not see release 0.5

### ISSUE THREAD

**Issue by devleaks** [PH-KDX/flightplandb-py#16]
Hello,
Pip does not see release 0.5. I noticed flightplandb/__init__.py still has release 0.4.1.
Could than be the cause?
Pierre

**Comment by PH-KDX** [comment]
Hadn't noticed that, I'll take a look. Thanks.

**Comment by PH-KDX** [comment]
Fixed!
https://pypi.org/project/flightplandb/0.5.0/
